### ISSUE TITLE
Need references for sampling artifacts and jittering

### ISSUE THREAD

**Issue by sankhesh** [aashish24/VTKVR#19]
Currently there is a citation missing in [results.tex](https://github.com/aashish24/VTKVR/blob/90c18042cf14f3123a55f66c261d4b41db9d2963/results.tex#L8-L17) for jittering.

IMHO, we need a citation for the sampling artifacts in volume rendering next to the following text:
```
Due to well established limitations
```

and a citation for the jittering technique used.

**Comment by alvarosan** [comment]
I agree Sankhesh, there is actually a citation but it seems to be currently ignored. I will make sure it is shown.

**Comment by sankhesh** [comment]
@alvarosan I added the ignore statement since there is no citation in the bib file.

**Comment by alvarosan** [comment]
Ha, I see. I probably forgot to add it then, will do that.  Thanks @sankhesh .

**Comment by sankhesh** [comment]
@alvarosan Thank you for fixing the bib item.

Do you have a reference for the limitations mentioned?
