### ISSUE TITLE
Need better images (and maybe, their citations)

### ISSUE THREAD

**Issue by sankhesh** [aashish24/VTKVR#20]
For ![raycasting.jpg](https://github.com/aashish24/VTKVR/raw/90c18042cf14f3123a55f66c261d4b41db9d2963/images/raycasting.jpg) and [vtk_volume_pipeline.pdf](https://github.com/aashish24/VTKVR/raw/90c18042cf14f3123a55f66c261d4b41db9d2963/vtk_volume_pipeline.pdf)

**Comment by aashish24** [comment]
@sankhesh is Steve back?

**Comment by aashish24** [comment]
we got new images from steve.
