### ISSUE TITLE
2D transfer functions

### ISSUE THREAD

**Issue by sankhesh** [aashish24/VTKVR#22]
Add sub-section on 2D transfer functions in results.tex

**Comment by cryos** [comment]
As I was saying to @alvarosan, can we ensure we acknowledge 'DOE Office of Science contract DE-SC0011385' for this work (or at least some portion of it), as it was developed as part of the Tomviz project, and will hopefully be exposed there soon.

**Comment by alvarosan** [comment]
Addressed by #28 .
